name: sums-up-server
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.8.0
  - aom=3.6.0
  - arrow-cpp=19.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cachetools=5.5.1
  - cairo=1.16.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cryptography=44.0.1
  - datasets=3.3.2
  - dav1d=1.2.1
  - deprecated=1.2.13
  - dill=0.3.8
  - dnspython=2.4.2
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.0
  - expat=2.6.4
  - fastapi=0.115.11
  - fastapi-cli=0.0.7
  - ffmpeg=6.1.1
  - ffmpeg-python=0.2.0
  - filelock=3.13.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - future=1.0.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-api-core=2.19.1
  - google-api-core-grpc=2.19.1
  - google-auth=2.38.0
  - google-cloud-speech=2.31.0
  - googleapis-common-protos=1.63.2
  - graphite2=1.3.14
  - grpcio=1.62.2
  - grpcio-status=1.62.2
  - h11=0.14.0
  - harfbuzz=10.2.0
  - httpcore=1.0.2
  - httptools=0.6.4
  - httpx=0.27.0
  - huggingface_hub=0.29.2
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - jinja2=3.1.5
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libgrpc=1.62.2
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - librsvg=2.56.3
  - libsentencepiece=0.2.0
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - mdurl=0.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.4
  - networkx=3.2.1
  - nomkl=3.0
  - numexpr=2.10.1
  - numpy=2.0.2
  - numpy-base=2.0.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - opentelemetry-api=1.26.0
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.50.7
  - pcre2=10.42
  - pip=25.0
  - pixman=0.40.0
  - propcache=0.2.0
  - proto-plus=1.26.0
  - protobuf=4.25.3
  - pyarrow=19.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pydantic-settings=2.6.1
  - pydub=0.25.1
  - pygments=2.15.1
  - pyopenssl=25.0.0
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-multipart=0.0.20
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch=2.5.1
  - pytube=15.0.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - rsa=4.7.2
  - safetensors=0.5.3
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=72.1.0
  - shellingham=1.5.0
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - sse-starlette=2.2.1
  - starlette=0.46.1
  - sympy=1.13.3
  - tesseract=5.2.0
  - tk=8.6.14
  - tokenizers=0.20.1
  - tqdm=4.67.1
  - transformers=4.45.2
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - uvicorn=0.32.1
  - uvicorn-standard=0.32.1
  - uvloop=0.21.0
  - watchfiles=0.24.0
  - websockets=15.0.1
  - wheel=0.45.1
  - wrapt=1.17.0
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - yt-dlp=2025.2.19
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - cachecontrol==0.14.2
      - firebase-admin==6.7.0
      - google-api-python-client==2.167.0
      - google-auth-httplib2==0.2.0
      - google-cloud-core==2.4.3
      - google-cloud-firestore==2.20.2
      - google-cloud-storage==3.1.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - httplib2==0.22.0
      - msgpack==1.1.0
      - pyjwt==2.10.1
      - pyparsing==3.2.3
      - uritemplate==4.1.1