BEGIN_SUMMARY = "[BEGIN-SUMMARY]"
END_SUMMARY = "[END-SUMMARY]"

BEGIN_EXAMPLE = "[BEGIN-EXAMPLE]"
END_EXAMPLE = "[END-EXAMPLE]"

BEGIN_PARAGRAPH = "[BEGIN-PARAGRAPH]"
END_PARAGRAPH = "[END-PARAGRAPH]"

BEGIN_METADATA = "[BEGIN-METADATA]"
END_METADATA = "[END-METADATA]"

BEGIN_TIMESTAMP = "[BEGIN-TIMESTAMP]"
END_TIMESTAMP = "[END-TIMESTAMP]"


def YIELD_DATA(key, value): 
    text = f"[BEGIN-DATA] [BEGIN-KEY] {key} [END-KEY] [BEGIN-VALUE] {value} [END-VALUE] [END-DATA]"
    return text.split()